spring:
  profiles:
    include: jwt, oauth, local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

#  # security logging
#  org.springframework.security: DEBUG